In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.0


In [8]:
# Check for the MPS(Metal Performance Shader) i.e Apple Metal GPU

# Is MPS even available? macOS 12.3+
print(torch.backends.mps.is_available())

# Was the current version of PyTorch built with MPS activated?
print(torch.backends.mps.is_built())

True
True


## Introduction to Tensors
### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [10]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [13]:
# Get tensor back as Python int
scalar.item()

7

In [14]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]
                       ])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([7, 8])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# TENSOR
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]
    ]
])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])