# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
random_tensor_A = torch.rand(7, 7)
random_tensor_A

tensor([[0.0641, 0.4588, 0.0419, 0.9692, 0.5314, 0.4872, 0.7348],
        [0.0949, 0.1400, 0.5282, 0.9366, 0.3097, 0.1068, 0.4517],
        [0.7259, 0.1007, 0.0850, 0.6996, 0.0612, 0.6261, 0.1187],
        [0.6996, 0.0764, 0.0306, 0.4883, 0.6349, 0.9521, 0.1624],
        [0.7368, 0.4185, 0.1012, 0.6055, 0.5912, 0.5763, 0.7778],
        [0.0628, 0.5225, 0.3991, 0.9256, 0.7354, 0.7299, 0.3902],
        [0.8384, 0.2204, 0.0134, 0.2236, 0.4202, 0.0999, 0.1143]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
random_tensor_B = torch.rand(1, 7)

# Perform matrix multiplication 
matrix_mul = torch.matmul(random_tensor_A, random_tensor_B.T)
matrix_mul

tensor([[0.9138],
        [0.7692],
        [0.3555],
        [0.5767],
        [1.0189],
        [1.1639],
        [0.4808]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
RANDOM_SEED = 42

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(1, 7)

# Matrix multiply tensors
matrix_mul_with_seed = torch.matmul(random_tensor_C, random_tensor_D.T)
matrix_mul_with_seed, matrix_mul_with_seed.shape


(tensor([[3.2618],
         [3.4084],
         [2.4866],
         [1.4525],
         [1.7079],
         [2.7291],
         [2.9204]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [24]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
def set_device():
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    return device

DEVICE = set_device()
print(f"Device: {DEVICE}")

# Create two random tensors on GPU
random_tensor_1 = torch.rand(size=(2,3)).to(DEVICE)
random_tensor_2 = torch.rand(size=(2, 3)).to(DEVICE)
random_tensor_1, random_tensor_2


Device: mps


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [26]:
# Perform matmul on tensor_A and tensor_B
matrix_multiplication = torch.matmul(random_tensor_1, random_tensor_2.T)
matrix_multiplication, matrix_multiplication.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='mps:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [28]:
# Find max
max = torch.max(matrix_multiplication)
# Find min
min = torch.min(matrix_multiplication)
max, min

(tensor(0.5617, device='mps:0'), tensor(0.3647, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [29]:
# Find arg max
max_index = torch.argmax(matrix_multiplication)

# Find arg min
min_index = torch.argmin(matrix_multiplication)
max_index, min_index

(tensor(3, device='mps:0'), tensor(0, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
MANUAL_SEED = 7
torch.manual_seed(MANUAL_SEED)
# Create random tensor
tensor_rand = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_squeezed = tensor_rand.squeeze()

# Print out tensors and their shapes
print(tensor_rand, tensor_rand.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
